root: artifacts

data_ingestion:
  root: artifacts/ingestion
  raw_data_dir: artifacts/ingestion/
  link: https://drive.google.com/file/d/1mlqzcDwiGC5W54hTMBETldwIIM_Q8gfN/view?usp=sharing
  raw_data_name: raw_data.csv

data_validation:
  raw_data_path: artifacts/ingestion/raw_data.csv
  expected_columns: [
    'class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
    'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
    'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
    'stalk-surface-below-ring', 'stalk-color-above-ring',
    'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
    'ring-type', 'spore-print-color', 'population', 'habitat']
  

data_transformation:
  raw_data_path: artifacts/ingestion/raw_data.csv
  processed_data_dir: artifacts/transformed
  X_train_path: artifacts/transformed/X_train.csv
  X_test_path: artifacts/transformed/X_test.csv
  y_train_path: artifacts/transformed/y_train.csv
  y_test_path: artifacts/transformed/y_test.csv

model_training:
  model_dir: artifacts/model
  model_file: artifacts/model/model.pkl
  # transformed dataset paths
  X_train: artifacts/transformed/X_train.csv
  X_test: artifacts/transformed/X_test.csv
  y_train: artifacts/transformed/y_train.csv
  y_test: artifacts/transformed/y_test.csv

model_evaluation:
  model_path: artifacts/model/model.pkl
  X_train: artifacts/transformed/X_train.csv
  y_train: artifacts/transformed/y_train.csv
  X_test: artifacts/transformed/X_test.csv
  y_test: artifacts/transformed/y_test.csv
  report_file: artifacts/evaluation/report.json
